/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppEditDialog: typeof import('./src/components/dialog/AppEditDialog.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    DingtalkConfig: typeof import('./src/components/dialog/notifier-configs/DingtalkConfig.vue')['default']
    FeishuConfig: typeof import('./src/components/dialog/notifier-configs/FeishuConfig.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingView: typeof import('./src/components/LoadingView.vue')['default']
    NotifierEditDialog: typeof import('./src/components/dialog/NotifierEditDialog.vue')['default']
    NotifyHelpDialog: typeof import('./src/components/dialog/NotifyHelpDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TelegramConfig: typeof import('./src/components/dialog/notifier-configs/TelegramConfig.vue')['default']
    TemplateEditDialog: typeof import('./src/components/dialog/TemplateEditDialog.vue')['default']
    TemplateImportDialog: typeof import('./src/components/dialog/TemplateImportDialog.vue')['default']
    TestNotificationDialog: typeof import('./src/components/dialog/TestNotificationDialog.vue')['default']
    WechatWorkConfig: typeof import('./src/components/dialog/notifier-configs/WechatWorkConfig.vue')['default']
    WechatWorkWebhookConfig: typeof import('./src/components/dialog/notifier-configs/WechatWorkWebhookConfig.vue')['default']
  }
}
