services:
  # 统一的通知应用服务 (前端 + 后端)
  notify-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notify-app:latest
    container_name: notify-app
    ports:
      - "8088:8088"
    volumes:
      - ./backend/.config:/config
    environment:
      - TZ=Asia/Shanghai
      # 管理接口Basic认证环境变量
      - NOTIFY_USERNAME=admin
      - NOTIFY_PASSWORD=admin
      # 从环境变量配置端口和配置文件路径
      - CONFIG_FILE=/config/config.yaml
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - PGID=912
      - PUID=912
      - UMASK=022
    restart: unless-stopped
    networks:
      - notify-network

networks:
  notify-network:
    driver: bridge 